# Intro to Numpy

When it comes to doing numerical work, Python by itself is rather slow. By slow we mean compared to languages like C and Fortran, which benefit from being **compiled** languages in which a program is preprocessed into machine code by a compiler. Python by contrast is an **interpreted** language, in which each line in a program is fed to an the Python interpreter in sequence, then executed. The flexiblity and ease of use that come with Python come at the cost of pure performance.

However, though Python code itself may be slow, Python can be used to run code that is written in a compiled language and already compiled. We will use a library (a.k.a., a Python *module*) that does exactly this underneath the hood to get fast performance for numerical operations on arrays.

In [1]:
import numpy

Importing a module is like taking a piece of equipment out of a storage locker and setting up on a lab bench. Importing the name `numpy` makes all the functions and classes (object types) available to us. The core data structure that `numpy` provides is known as the `numpy` array:

In [2]:
somenums = numpy.array([1, 2, 3, 4])
print(somenums)

[1 2 3 4]


A numpy array looks superfically similar to a `list`, which is a builtin to Python. They are fundamentally different, however, in how they both work and how they exist in memory. `numpy` arrays don't store references to other objects, but instead point to contiguous blocks of memory in which each element is of exactly the same data type. For instance, we just made an array of 64 bit integers:

In [3]:
somenums.dtype

dtype('int64')

In [4]:
# this will give an array with a string dtype
numpy.array(['a string', 10])

array(['a string', '10'], 
      dtype='<U8')

In [5]:
# this will give an array of 64 bit floats
floats = numpy.array([63.3, -5.0, 1])
print(floats)

[ 63.3  -5.    1. ]


In [6]:
floats.dtype

dtype('float64')

Also, because arrays are not a collection of objects but are a single object of identically sized pieces of data, they cannot be resized. To add elements to an array, one must create a new array.

In [7]:
# this will create a new array with repeated elements
numpy.hstack([somenums, somenums])

array([1, 2, 3, 4, 1, 2, 3, 4])

## Multidimensionality, indexing, and slicing

`numpy` arrays can be of any dimensionality, not just 1-D. It's common to encounter 2-D arrays, and for illustration we'll look at the position of a particle in three dimensions with time:

In [8]:
import numpy as np

In [9]:
# generate x, y, z positions
nframes = 100
x = np.cos(np.linspace(0, 20, nframes))
y = np.sin(np.linspace(0, 10, nframes))
z = np.sin(np.pi * np.linspace(0, 5, nframes))

# put them all in a single array; this gives
# an array with 3 rows and nframes columns
position = np.array([x, y, z])

# we want the transpose array for now
position = position.transpose()

In [10]:
position.shape

(100, 3)

Now say we wanted to examine the position of the particle in the very first frame, we could do:

In [11]:
position[0]

array([ 1.,  0.,  0.])

to extract it. Notice that indexing starts at 0, as is the convention in Python.

What about the third frame?

In [12]:
position[2]

array([ 0.91948007,  0.20064886,  0.31203345])

In zero-based terms, this we would call the "first frame" the zeroth frame, and so on. To avoid confusion we'll assume this from now on.

What if we wanted a bunch of frames, but only the 5th through the 72nd? It should have 68 rows:

In [13]:
position[5:73].shape

(68, 3)

Notice the **slicing** notation. Remember, this should be read as

> "Get each row in the array starting from the row at index 5 up to and not including the row at index 73."

We could even coarse-grain by slicing out every fifth row in this range:

In [21]:
position[5:73:5].shape

(14, 3)

Now what if we wanted a specific *element* of the array? Indexing works for this too:

In [22]:
position[42, 1]

-0.89158425733514024

This is the y-position of the 42nd frame.

### Breakout:

Now say we wanted to calculate the mean x-position of the particle over all time. We could 

## Array methods (or, arrays are objects)