# Numpy for arrays! 

In [1]:
import numpy as np

In [2]:
a = np.arange(0, 5)

In [3]:
a

array([0, 1, 2, 3, 4])

Calculate
$$
m_i = \frac{1}{2} (a_i + a_{i+1})
$$

## loops 

In [4]:
m = np.zeros(len(a)-1)
for i in range(len(a)-1):
    m[i] = 0.5*(a[i] + a[i+1])
m    

array([0.5, 1.5, 2.5, 3.5])

## arrays 

### Can we avoid the loop?

* `a[i]` covers the elements `[0, 1, 2, 3, 4]`
* `a[i+1]` covers the elements `[1, 2, 3, 4, 5]`

Think about shifting the arrays:
```
[0 1 2 3 4]
  [0 1 2 3 4]
-------------
   1 3 5 7
               * 0.5
=====================
  0.5 1.5 2.5 3.5  
```    

Can we get these numbers by slicing?

```
  [1 2 3 4]  = a[1:]
  [0 1 2 3]  = a[:-1]
-----------
   1 3 5 7   = a[1:] + a[:-1]
```   

Think about these equivalences between loop and array approach:

* `a[i]` is like `a[:-1]`
* `a[i+1]` is like `a[1:]`

### Use the sliced arrays 

In [7]:
m = 0.5*(a[:-1] + a[1:])
m

array([0.5, 1.5, 2.5, 3.5])

Using sliced arrays is
* more readable (more elegant)
* faster 

**Prefered way to work with arrays**

### Speed-up

How fast is it?

In [5]:
%%timeit
for i in range(len(a)-1):
    m[i] = 0.5*(a[i] + a[i+1])

11.5 µs ± 308 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
%%timeit
m = 0.5*(a[:-1] + a[1:])

2.46 µs ± 234 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
m

array([0.5, 1.5, 2.5, 3.5])

# Exercise
Use *numpy arrays* to calculate for a vector $\mathbf{b}$ of length $N$

$$
y_i = \frac{1}{2}(b_{i-1} + b_{i+1})
$$

and set $y_0 = y_{N-1} = 100$.

In [12]:
b = np.arange(11)

In [13]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Solution 

In [14]:
y = np.zeros_like(b)
y[1:-1] = 0.5*(b[:-2] + b[2:])
y[0] = y[-1] = 100

y

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100])