# Numpy for arrays! 

In [1]:
import numpy as np

In [2]:
a = np.arange(1, 6)

In [3]:
a

array([1, 2, 3, 4, 5])

Calculate
$$
m_i = \frac{1}{2} (a_i + a_{i+1})
$$

## loops 

In [4]:
m = np.zeros(len(a)-1)

In [20]:
%%timeit
for i in range(len(a)-1):
    m[i] = 0.5*(a[i] + a[i+1])

10.3 µs ± 77.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [7]:
m

array([1.5, 2.5, 3.5, 4.5])

## arrays 

In [19]:
%%timeit
m = 0.5*(a[:-1] + a[1:])

2.13 µs ± 28.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [21]:
m

array([1.5, 2.5, 3.5, 4.5])